CR-1257 | tidying up the logging
ONSdigital/census-rh-ui pull request #124
Opened 2020-10-13 15:36 UTC by akritisinhaa

This ticket involved reviewing the logging in RHUI. There were some points raised regarding it and was discussed and agreed with Paul and the changes have been made accordingly.

For more information please see the ticket https://collaborate2.ons.gov.uk/jira/browse/CR-1257. 
To know more about the context of the changes please look at the **Questions** tab in the spreadsheet attached to this ticket and Paul's response on the ticket.

2020-10-14 10:55 UTC, Paul-Joel requested changes
Couple of changes to the text of the messages

2020-10-14 10:55 UTC, Paul-Joel commented on app/start_handlers.py
> +            logger.info('adlocation error')
Log text should be 'no adlocation present' - the KeyError happens when there is no adlocation provided, which is the normal behaviour

2020-10-14 10:55 UTC, Paul-Joel commented on app/start_handlers.py
> +                logger.error('invalid access code', client_ip=request['client_ip'])
Log text needs to be something like 'error processing access code' - this error is triggered when RHSvc returns any error not triggered by an invalid code

2020-10-14 12:05 UTC, Paul-Joel approved these changes
LGTM

2020-10-15 07:00 UTC, rpcatling approved these changes

2020-10-15 07:00 UTC, merged