CR-1302 Bug fix for request fulfilments
ONSdigital/census-rh-ui pull request #131
Opened 2020-10-27 10:57 UTC by Paul-Joel

Signed-off-by: Paul-Joel <paul.joel@ons.gov.uk>

# Motivation and Context
Fix bug introduced by RHSvc change

# What has changed
An update to RHSvc changed the return value for language in the get_fulfilments call, breaking RHUI when more than one code was returned. This change makes RHUI use the revised values for language.

# How to test?
Request a fulfilment for a welsh postcode (in english or welsh), and confirm journey completes without error

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1302

2020-10-29 15:18 UTC, MartinHumphrey requested changes
It all works but found treatment of test data inconsistent?
You have updated one test data file to reflect the latest RH svc get fulfillments returned JSON  but have not altered the other three effected files, just changing the required value here but not reflecting the other changed JSON values?

2020-10-29 15:18 UTC, MartinHumphrey commented on tests/test_data/rhsvc/get_fulfilment_single_sms.json
> +       "language": "E",
A lot of the attributes remain the same allowing this to work but not quite accurate for a RH service mocked get fulfilment return JSON?

2020-10-30 13:35 UTC, MartinHumphrey approved these changes

2020-10-30 14:19 UTC, AmeeshKutthan approved these changes
Code Review:

The fulfilment journey completes successfully.
In addition, I also tested the Individual Response journey, and that also completed successfully 
All screenshots have been detailed below:

<img width="1792" alt="Screenshot 2020-10-30 at 13 59 40" src="https://user-images.githubusercontent.com/72972620/97715694-a0444500-1aba-11eb-878e-fd0c72fb1bb0.png">

<img width="1792" alt="Screenshot 2020-10-30 at 13 59 54" src="https://user-images.githubusercontent.com/72972620/97715710-a4706280-1aba-11eb-8ea5-c8c51814eb65.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 00 16" src="https://user-images.githubusercontent.com/72972620/97715714-a508f900-1aba-11eb-9c9b-96e1b5c90cfe.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 00 25" src="https://user-images.githubusercontent.com/72972620/97715716-a5a18f80-1aba-11eb-8c38-5ad83af03197.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 00 36" src="https://user-images.githubusercontent.com/72972620/97715723-a63a2600-1aba-11eb-967f-5be8116b5877.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 00 57" src="https://user-images.githubusercontent.com/72972620/97715728-a76b5300-1aba-11eb-8e3d-82251d0fa708.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 05 34" src="https://user-images.githubusercontent.com/72972620/97715733-a803e980-1aba-11eb-83a5-51348017e417.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 05 51" src="https://user-images.githubusercontent.com/72972620/97715740-a89c8000-1aba-11eb-8880-07cd29d49eb6.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 06 09" src="https://user-images.githubusercontent.com/72972620/97715742-a9351680-1aba-11eb-9a8e-66717cd50aaf.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 06 26" src="https://user-images.githubusercontent.com/72972620/97715745-a9cdad00-1aba-11eb-89e1-2bd4b0536342.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 06 36" src="https://user-images.githubusercontent.com/72972620/97715750-aafeda00-1aba-11eb-93b1-96e6323833d3.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 06 45" src="https://user-images.githubusercontent.com/72972620/97715753-ab977080-1aba-11eb-8b42-0683eceeb847.png">
<img width="1792" alt="Screenshot 2020-10-30 at 14 06 53" src="https://user-images.githubusercontent.com/72972620/97715757-ac300700-1aba-11eb-896e-0da0208a392b.png">
<img width="1792" alt="Screenshot 2020-10-30 at 14 07 16" src="https://user-images.githubusercontent.com/72972620/97715763-acc89d80-1aba-11eb-9a6c-06d93d9c71ca.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 07 27" src="https://user-images.githubusercontent.com/72972620/97715765-ad613400-1aba-11eb-9a6d-e7f6e6c46bb1.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 07 35" src="https://user-images.githubusercontent.com/72972620/97715767-ae926100-1aba-11eb-8084-dbb766407024.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 07 58" src="https://user-images.githubusercontent.com/72972620/97715769-af2af780-1aba-11eb-9df6-3e1f832f95d1.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 08 09" src="https://user-images.githubusercontent.com/72972620/97715772-afc38e00-1aba-11eb-908f-a0404c98f0f2.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 08 16" src="https://user-images.githubusercontent.com/72972620/97715778-b05c2480-1aba-11eb-8a76-6282fcee9017.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 08 27" src="https://user-images.githubusercontent.com/72972620/97715783-b0f4bb00-1aba-11eb-8f33-a05110da25de.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 09 01" src="https://user-images.githubusercontent.com/72972620/97715784-b18d5180-1aba-11eb-8cc0-dd0b033f1107.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 09 11" src="https://user-images.githubusercontent.com/72972620/97715788-b2be7e80-1aba-11eb-8d57-b283c499cb0d.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 09 19" src="https://user-images.githubusercontent.com/72972620/97715792-b3571500-1aba-11eb-8c9a-30b0dda2f1e6.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 09 26" src="https://user-images.githubusercontent.com/72972620/97715794-b4884200-1aba-11eb-9bb3-84d9f24fb2dd.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 10 53" src="https://user-images.githubusercontent.com/72972620/97715797-b520d880-1aba-11eb-9ffd-fa786b845bfc.png">

<img width="1792" alt="Screenshot 2020-10-30 at 14 11 39" src="https://user-images.githubusercontent.com/72972620/97715799-b5b96f00-1aba-11eb-940a-7f226be04362.png">

2020-10-30 14:23 UTC, merged