Cr 1212 multiple fulfilment codes
ONSdigital/census-rh-ui pull request #133
Opened 2020-10-29 17:35 UTC by Paul-Joel

# Motivation and Context
Update to integrate with revised RHSvc for multiple fulfilments and rate limiting

# What has changed
Addition of new error handler for 429 Too Many Requests
Change to build fulfilment request array rather than a single value
Update to request fulfilment endpoint calls, to include single clientIP, and code to extract single IP
Additional 429 error unit tests

# How to test?
Has been tested alongside other updates in RHDev
Cannot currently be tested locally as locally run site does not generate an IP, which causes an error in RHSvc

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1212

# Screenshots (if appropriate):

2020-10-30 11:17 UTC, rpcatling requested changes
All good apart from the unit tests are broken!

2020-10-30 14:26 UTC, rpcatling approved these changes

2020-11-02 13:46 UTC, AmeeshKutthan reviewed
Code is fine. Very neat and tidy and conforms to python standards.
Easily maintainable/extensible also.

2020-11-02 16:18 UTC, AmeeshKutthan approved these changes

2020-11-02 16:19 UTC, merged