Cr 1228 nisra redirecting
ONSdigital/census-rh-ui pull request #136
Opened 2020-11-10 18:05 UTC by Paul-Joel

# Motivation and Context
Introduces region specific redirecting/messaging

# What has changed
Adds region specific trapping - the entered UAC or chosen address must now be appropriate for the site version, ie: An NI UAC cannot be used on the /en or /cy sites, only on the /ni sites. If the user is on the wrong 'site' for the data supplied they now get a page saying that they are on the wrong site, with a link to the correct one (same principle as for Scotland), rather than the site shifting them over.
This is deemed a better solution, as the nav and footer links are for the wrong site, and a user could get incorrect help, or call the wrong contact centre

All unit tests and test data have been updated to have version for all 3 regions

Required cucumber updates were stand-alone and have already been merged.

# How to test?
Enter a N UAC on the /en/start/ version
Enter a E or W UAC on teh /ni/start/ version

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1228

# Screenshots (if appropriate):

2020-11-13 16:26 UTC, cookel2 requested changes
Hi Paul, it looks good. I'm only requesting a change to the test data. However, I think it's also worth saying that I accidentally tested with an unlinked UAC at one point. I entered it onto the start page for England. It then prompted me for a postcode so I gave it the NI one (BT38 9PT) just to see what would happen. It then gave me the "Sorry, something went wrong" message, which makes sense but might be something that we could improve if there's time.

2020-11-16 12:49 UTC, MartinHumphrey requested changes
Minor comments on redundant attributes passed in context to templates.
The new files created in this PR need a newline added to the end. GitHub complaining "No new line at end of file" e.g.  common-address-in-england.html.

2020-11-16 15:25 UTC, Paul-Joel commented on app/start_handlers.py
> +        locale = 'en'
locale is still needed - although the page has no text marked for translation, passing locale through also sets the html lang attribute (and possibly other settings)

2020-11-16 15:25 UTC, Paul-Joel commented on app/start_handlers.py
> +            'locale': locale,
As above

2020-11-16 15:25 UTC, Paul-Joel commented on app/start_handlers.py
> +        locale = 'en'
As above

2020-11-16 15:25 UTC, Paul-Joel commented on app/start_handlers.py
> +            'locale': locale,
As above

2020-11-16 15:27 UTC, Paul-Joel commented on app/common_handlers.py
> +        locale = 'en'
As above

2020-11-16 15:31 UTC, Paul-Joel commented on app/common_handlers.py
> +        locale = 'en'
As above

2020-11-16 19:54 UTC, Paul-Joel commented on tests/test_data/address_index/uprn_wales.json
> +            "uprn": "10023122451",
Not really a big deal, as only the Region value is used for testing, however I have updated the test data for Wales and Scotland to be representative

2020-11-16 19:54 UTC, Paul-Joel commented on app/start_handlers.py
> +            'display_region': display_region,
Removed

2020-11-16 19:55 UTC, Paul-Joel commented on app/start_handlers.py
> +            'display_region': display_region,
Removed

2020-11-16 19:56 UTC, Paul-Joel commented on app/common_handlers.py
> +            'display_region': display_region,
Cleaned this up to leave only the needed values

2020-11-16 19:56 UTC, Paul-Joel commented on app/common_handlers.py
> +        display_region = 'ni'
Cleaned up

2020-11-16 19:57 UTC, Paul-Joel commented on app/common_handlers.py
> +            'user_journey': user_journey,
Cleaned up

2020-11-16 20:07 UTC, Paul-Joel commented on app/start_handlers.py
> +                raise HTTPFound(request.app.router['StartConfirmAddress:get'].url_for(display_region='en'))
Updated

2020-11-17 11:09 UTC, MartinHumphrey approved these changes

2020-11-17 14:33 UTC, cookel2 approved these changes

2020-11-17 14:33 UTC, cookel2 commented on tests/test_data/address_index/uprn_wales.json
> +            "uprn": "100100011957",
looks good

2020-11-17 14:35 UTC, merged