Cr 1323 implement loader buttons
ONSdigital/census-rh-ui pull request #163
Opened 2020-12-18 16:43 UTC by Paul-Joel

# Motivation and Context
Adds the 'loader' parameter to buttons that trigger an external interaction in RHUI

# What has changed
Updates to various buttons in RHUI to add the 'loader' setting. This setting prevents the button from being pressed more than once, to prevent multiple submissions whilst the page is completing its processing.
It has been added to any button whose submission triggers an interaction outside of RHUI, ie with RHSvc, AIMS or the ADLookup API where a delay could be possible

No RHCucumber updates are required

# How to test?
Delay a response from the services and confirm that the button cannot be re-pressed. Button should so a spinning icon whilst waiting.

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1323
https://ons-design-system.netlify.app/components/button/#loader

2020-12-22 15:01 UTC, cookel2 requested changes
It looks like this functionality also needs to be added to the "Access census" button, on the start page, because it calls the uacs endpoint in RHSVC e.g. http://localhost:8071/uacs/3d0ee1b49661017aeeee14585d18e49de65f0d046f668280e2040b6565741301

2021-01-05 10:29 UTC, cookel2 approved these changes
looks good

2021-01-05 14:53 UTC, MartinHumphrey reviewed
Other scenarios for consideration:

- common-select-address.html. On post redirects to CommonConfirmAddress:get which calls AddressIndex.get_ai_uprn. If no address selection is made it will also call AddressIndex.get_postcode_return again before redisplaying the form.
-  start-address-changed.html. On post calls call.questionnaire which in turn calls RHService.post_surveylaunched. 
- start-unlinked-linked.html. On post calls call.questionnaire which in turn calls RHService.post_surveylaunched. 

While looking at requests to other services, in the module error_handlers.py the setup function defines how to treat http 500(Internal Server Error) and 503 (Service Unavailable) responses. Should we also define HTTP 504 (Gateway Timeout) which seems to be a favourite of Google to ensure users don't see a blank page with this response, perhaps also HTTP 502 (Bad Gateway)?  Hopefully will never happen.

2021-01-05 16:54 UTC, MartinHumphrey approved these changes

2021-01-05 16:55 UTC, merged