Cr 1467 select address 403 fix
ONSdigital/census-rh-ui pull request #165
Opened 2021-01-07 11:02 UTC by Paul-Joel

# Motivation and Context
Changes how 'select-address' page is built to stop WAF rules being violated

# What has changed
Changed radio 'name' to remove problem term 'select'
Removed redundant JSON from radio 'value', so that the field only contains the UPRN value
Added text variant for only 1 address match
Updated effected unit tests

Requires matching RHCuc update due to field name change

# How to test?
Tested in dev

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1467

# Screenshots (if appropriate):

2021-01-08 09:22 UTC, cookel2 approved these changes
looks good

2021-01-11 12:18 UTC, MartinHumphrey requested changes
Minor flake8 style changes

2021-01-11 12:25 UTC, Paul-Joel commented on app/utils.py
> -                json.dumps({
Removed

2021-01-11 12:25 UTC, Paul-Joel commented on app/utils.py
Extra blank left over from delete - removed

2021-01-11 12:56 UTC, MartinHumphrey approved these changes

2021-01-11 13:23 UTC, merged