CR-1456 Add log identifier
ONSdigital/census-rh-ui pull request #198
Opened 2021-02-10 13:52 UTC by MartinHumphrey

# Motivation and Context
Enable logs to be filtered to associate previous log statements generated from an individual client and provide context in investigating client errors, warnings.

# What has changed
Middleware has been introduced so that for every request a client_id and trace are added to the request object and available to log statements.
The trace is taken from the X-Cloud-Trace-Context header which is added to a request by Google and has the specification `X-Cloud-Trace-Context: TRACE_ID/SPAN_ID;o=TRACE_TRUE`. A trace is unique to a client request and is used to group logs within a client request process. A span would represent a unit of work within a trace, if for instance we were using OpenTelemetry or OpenCensus client libraries to instrument the code and generate logs and metrics and display latency data in Cloud Trace. Using these could have performance implications in production and not to be considered at this stage, so I have simply added the trace to log statements to group request logs and ignored span as unnecessary noise with no purpose for production.
The client_id is used to group all requests from a client during a session. It is stored within a session and made available by adding to the incoming request if available in the session, or created if not.
I have also taken the opportunity to make the client_ip available in the same manner, removing the frequent calls to `self.setup_request(request)` in each view handler.

# How to test?
New unit tests added. Run against cucumber tests. I have currently deployed this code to the development environment so you can generate log statements and see the client_id and trace in the jsonPayload data. 

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1456

2021-02-12 12:09 UTC, rpcatling requested changes
a few missing bits of logging.

2021-02-12 12:09 UTC, rpcatling commented on app/utils.py
> +                    client_id=request['client_id'],
missing client_ip ?

2021-02-15 14:13 UTC, rpcatling commented on app/error_handlers.py
> +                logger.debug('redirecting to index',
done

2021-02-15 14:13 UTC, rpcatling commented on app/request.py
> +            logger.debug('successfully connected to service',
done

2021-02-15 14:14 UTC, rpcatling commented on app/request_handlers.py
> +                                client_id=request['client_id'],
done

2021-02-15 14:14 UTC, rpcatling commented on app/request_handlers.py
> +            logger.info('no session - directing to enter address',
done

2021-02-15 14:15 UTC, rpcatling commented on app/utils.py
> +                    client_id=request['client_id'],
done

2021-02-15 14:15 UTC, rpcatling commented on app/common_handlers.py
>                                      client_ip=request['client_ip'], status_code=ex.status, uac_hashed=hashed_uac_value)
done

2021-02-15 14:15 UTC, rpcatling commented on app/error_handlers.py
> +    logger.warn('attempt to use an inactive access code', client_id=request['client_id'], trace=request['trace'])
done

2021-02-15 14:16 UTC, rpcatling commented on app/start_handlers.py
> +                        client_id=request['client_id'], trace=request['trace'], region_of_site=display_region)
done

2021-02-15 14:16 UTC, rpcatling approved these changes

2021-02-15 16:07 UTC, PeterBochel approved these changes

2021-02-17 13:16 UTC, philwhiles approved these changes
Happy with this change - travis built image was tested in greylodge, no performance impact, tests passed and we are happy with the change as evidenced in the k8s log

2021-02-17 13:16 UTC, merged