Cr 1704 ad lookup add description
ONSdigital/census-rh-ui pull request #211
Opened 2021-02-24 12:35 UTC by Paul-Joel

# Motivation and Context
Changes to AD lookup output to match revised data format and designs

# What has changed
Fix to cope with addresses now being newline separated and not comma separated
Fix to formatting of google map link following previous DS update invalidating implementation
Addition of description field write out following design change
Tweak to test data to match revised data formats/design

Note: duplicate postcode mentioned in ticket was a data issue, incorrect class already fixed

# How to test?

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1704

2021-02-24 14:28 UTC, MartinHumphrey approved these changes
Would have liked to run locally against the real API but LGTM.

2021-02-25 17:28 UTC, rpcatling requested changes

2021-02-25 17:28 UTC, rpcatling commented on app/templates/support_centre_list_of_centres.html
>              <div><span class="u-mb-s distance">{{ _('%(distance_in_miles)s miles away', distance_in_miles=centre['distanceInMiles'] )|safe }}</span></div>
should there be a change here ?  JIRA says "incorrect class on distance tag"

2021-02-25 17:50 UTC, rpcatling commented on app/templates/support_centre_list_of_centres.html
>              <div><span class="u-mb-s distance">{{ _('%(distance_in_miles)s miles away', distance_in_miles=centre['distanceInMiles'] )|safe }}</span></div>
Paul informs me the change was made in a previous commit

2021-02-25 17:50 UTC, rpcatling approved these changes

2021-02-25 22:38 UTC, merged