Cr 1763 i pv6
ONSdigital/census-rh-ui pull request #216
Opened 2021-03-03 17:06 UTC by Paul-Joel

Tweaks to IP extraction to cope with IPv6 values, and update/split of unit tests

Signed-off-by: Paul-Joel <paul.joel@ons.gov.uk>

# Motivation and Context
Tweaks to IP extraction to cope with IPv6 values, and update/split of unit tests

# What has changed
Changes to ip split and associated unit tests

No Cucumber updates required

# How to test?

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1763

2021-03-03 17:10 UTC, rpcatling approved these changes
LGTM

2021-03-04 15:04 UTC, MartinHumphrey commented on app/utils.py
> +            single_ip_validation_pattern = re.compile(r'^[0-9.]*$')
The '*' matches 0 or more repetitions of the character set, would "+" matching 1 or more repetitions be better?

2021-03-04 15:24 UTC, MartinHumphrey approved these changes
Two comments about regular expression but don't make a significant difference.

2021-03-04 15:24 UTC, MartinHumphrey commented on app/utils.py
> +            ip_validation_pattern = re.compile(r'^[0-9a-zA-Z.:,\s]*$')
The '*' matches 0 or more repetitions of the character set, would "+" matching 1 or more repetitions be better?

2021-03-04 15:24 UTC, MartinHumphrey commented on app/utils.py
> +            single_ip_validation_pattern = re.compile(r'^[0-9.]*$')
The '*' matches 0 or more repetitions of the character set, would "+" matching 1 or more repetitions be better?

2021-03-04 15:28 UTC, rpcatling requested changes
Initial regex needs to let through junk at the beginning.

2021-03-08 11:26 UTC, PeterBochel approved these changes

2021-03-08 11:32 UTC, rpcatling approved these changes

2021-03-08 12:13 UTC, merged