CR-1791 BFPO Regex Change
ONSdigital/census-rh-ui pull request #227
Opened 2021-03-11 16:45 UTC by Paul-Joel

Removed BFPO part of regex, and added 'BF' as valid start letters

Signed-off-by: Paul-Joel <paul.joel@ons.gov.uk>

# Motivation and Context
Update to bring RH into line with AIMS for BF and BFPO

# What has changed
Changes to existing regex

# How to test?
Check that a BFPO postcode is rejected in RH as invalid
Check that a BF postcode (BF1 3AG) routes to AIMS and doesn't receive an error in response

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1791

2021-03-11 16:59 UTC, PeterBochel approved these changes

2021-03-12 08:17 UTC, rpcatling requested changes
one or two unit tests required

2021-03-12 08:35 UTC, rpcatling commented
How about :

```
    def test_validate_postcode_valid_BritishForces(self):
        locale = 'en'
        # When validate_postcode is called nothing happens
        ProcessPostcode.validate_postcode('BF1 3AG', locale)
        ProcessPostcode.validate_postcode('BF1 2BA', locale)
        ProcessPostcode.validate_postcode('BF1 3BN', locale)

    def test_validate_postcode_invalid_BritishForces(self):
        postcode = 'BFPO 105'
        locale = 'en'

        # When validate_postcode is called
        with self.assertRaises(InvalidDataError) as cm:
            ProcessPostcode.validate_postcode(postcode, locale)
        # Then an InvalidDataError is raised
        self.assertEqual(
            'Enter a valid UK postcode',
            str(cm.exception)
        )
        # With the correct message
```

in the `test_utils.py`. ?

2021-03-12 09:14 UTC, rpcatling approved these changes

2021-03-12 13:51 UTC, PeterBochel approved these changes

2021-03-12 13:58 UTC, rpcatling commented
Update OK by me

2021-03-12 17:14 UTC, philwhiles approved these changes

2021-03-12 17:15 UTC, merged